### ISSUE TITLE
[suggestion] remember last save to clipboard/pictures/documents

### ISSUE THREAD

**Issue by bartv42** [pop-os/cosmic-screenshot#37] opened 2024-07-17 06:18 UTC
I tend to capture to my clipboard most of the time, and right now the screenshot tool always reverts back to 'save to pictures'. Having it remember my last action would save 2 clicks :)

**Comment by leviport** [comment] 2024-07-17 13:25
Duplicate of https://github.com/pop-os/cosmic-screenshot/issues/29

**Closed by leviport** 2024-07-17 13:25 UTC
